### ISSUE TITLE
Document the mechanism

### ISSUE THREAD

**Issue by johnslavik** [alexmojaki/eval_type_backport#5]
I had a tough moment understanding this solution is better than [mine](https://github.com/bswck/modern_types#readme).

But I also realized that I can help with precise documenting:
- How the transformation takes place,
- Edge cases ([I think I found one](https://github.com/alexmojaki/eval_type_backport/issues/9)),
- How to use it outside of pydantic.

Shall I?

**Comment by alexmojaki** [comment]
Yes, thank you!

**Comment by johnslavik** [comment]
# Roadmap
- [ ] Technical explanation of the backport (how AST is used to transform type hints, how are replacements determined, what are they, how does the behavior change in 3.9 compared to 3.8)
- [ ] Troubleshooting (how to solve known problems? E.g. #9)
- [ ] How to use outside of pydantic.

**Comment by johnslavik** [comment]
Priority bump: #11.

**Comment by johnslavik** [comment]
@alexmojaki you can assign me to this.

**Comment by johnslavik** [comment]
@alexmojaki Would you like to host docs on [RTD](https://readthedocs.io/)?
